### ISSUE TITLE
Add support for Configuration Profiles

### ISSUE THREAD

**Issue by aschwanb** [BadStreff/git2jss#35]
Hello

First of all: Thank you for writing this great tool!

This is a feature request and not an issue as such. Do you have any planes to add support for configuration profiles?
Or would you be willing to accept a PR with this functionality?

**Comment by apizz** [comment]
At my last job, I took https://github.com/rtrouton/rtrouton_scripts/tree/master/rtrouton_scripts/Casper_Scripts/Jamf_Pro_Mac_Configuration_Profile_Download as inspiration for the download piece.  But this was more to document changes performed in Jamf, rather than to achieve a similar push mechanism that git2jss achieves for scripts & EAs.

**Comment by badstreff** [comment]
Hey @aschwanb apologies for the slow reply here, there were some thoughts about doing this but it wasn't something I ever got around to and unfortunately isn't something I will likely be able to commit to any time in the future as I've switched roles and not longer have a JAMF instance to test against.

PRs are welcome but I'm unable to test them :)

**Comment by aschwanb** [comment]
Hey @badstreff 
Thank you for your reploy. I'll go with the tool suggested by @apizz to document our existing profiles.

I'll close this issue for now.
